// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TreeNode from "./TreeNode.res.js";
import * as Core__List from "@rescript/core/src/Core__List.res.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function binaryTreeInorderTraversal(root) {
  var traverse = function (_resultStack, _curr, _workingStack) {
    while(true) {
      var workingStack = _workingStack;
      var curr = _curr;
      var resultStack = _resultStack;
      if (curr !== undefined) {
        _workingStack = {
          hd: curr,
          tl: workingStack
        };
        _curr = curr.left;
        continue ;
      }
      if (!workingStack) {
        return resultStack;
      }
      var popped = workingStack.hd;
      _workingStack = workingStack.tl;
      _curr = popped.right;
      _resultStack = {
        hd: popped.val,
        tl: resultStack
      };
      continue ;
    };
  };
  return Core__List.toArray(Core__List.reverse(traverse(/* [] */0, root, /* [] */0)));
}

var n5 = TreeNode.make(5, Caml_option.some(TreeNode.make(3, undefined, undefined)), Caml_option.some(TreeNode.make(7, undefined, undefined)));

var n15 = TreeNode.make(15, undefined, Caml_option.some(TreeNode.make(18, undefined, undefined)));

var root1 = TreeNode.make(10, Caml_option.some(n5), Caml_option.some(n15));

var r1 = binaryTreeInorderTraversal(root1);

console.log("r1: ", r1);

export {
  binaryTreeInorderTraversal ,
  n5 ,
  n15 ,
  root1 ,
  r1 ,
}
/* n5 Not a pure module */
