// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";

function make(val, branchesOpt) {
  var branches = branchesOpt !== undefined ? Caml_option.valFromOption(branchesOpt) : undefined;
  return {
          val: val,
          branches: branches
        };
}

export {
  make ,
}
/* No side effect */
