// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TreeNode from "./TreeNode.res.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function rootEqualsSumOfChildren(root) {
  if (root === undefined) {
    return false;
  }
  var left = root.left;
  var right = root.right;
  if (left !== undefined && right !== undefined) {
    return root.val === (left.val + right.val | 0);
  } else {
    return false;
  }
}

var n4 = TreeNode.make(4, undefined, undefined);

var n6 = TreeNode.make(6, undefined, undefined);

var root1 = TreeNode.make(10, Caml_option.some(n4), Caml_option.some(n6));

var r1 = rootEqualsSumOfChildren(root1);

console.log("r1: ", r1);

export {
  rootEqualsSumOfChildren ,
  n4 ,
  n6 ,
  root1 ,
  r1 ,
}
/* n4 Not a pure module */
