// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TreeNode from "./TreeNode.res.js";
import * as Core__Int from "@rescript/core/src/Core__Int.res.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.js";

function sumRootToLeafNumbers(root) {
  if (root !== undefined) {
    var _sum = 0;
    var _stack = {
      hd: [
        root,
        ""
      ],
      tl: /* [] */0
    };
    while(true) {
      var stack = _stack;
      var sum = _sum;
      if (!stack) {
        return sum;
      }
      var match = stack.hd;
      var node = match[0];
      var right = node.right;
      var left = node.left;
      var rest = stack.tl;
      var concatenated = match[1] + node.val.toString();
      if (left !== undefined) {
        if (right !== undefined) {
          _stack = {
            hd: [
              left,
              concatenated
            ],
            tl: {
              hd: [
                right,
                concatenated
              ],
              tl: rest
            }
          };
          continue ;
        }
        _stack = {
          hd: [
            left,
            concatenated
          ],
          tl: rest
        };
        continue ;
      }
      if (right !== undefined) {
        _stack = {
          hd: [
            right,
            concatenated
          ],
          tl: rest
        };
        continue ;
      }
      _stack = rest;
      _sum = sum + Core__Option.mapOr(Core__Int.fromString(concatenated, undefined), 0, (function (s) {
              return s;
            })) | 0;
      continue ;
    };
  } else {
    return 0;
  }
}

var n5 = TreeNode.make(5, Caml_option.some(TreeNode.make(3, undefined, undefined)), Caml_option.some(TreeNode.make(7, undefined, undefined)));

var n15 = TreeNode.make(15, undefined, Caml_option.some(TreeNode.make(18, undefined, undefined)));

var root1 = TreeNode.make(10, Caml_option.some(n5), Caml_option.some(n15));

var r1 = sumRootToLeafNumbers(root1);

console.log("r1: ", r1);

export {
  sumRootToLeafNumbers ,
  n5 ,
  n15 ,
  root1 ,
  r1 ,
}
/* n5 Not a pure module */
