// Generated by ReScript, PLEASE EDIT WITH CARE


function substringsSizeThreeDistinctChars(str) {
  var expandWindow = function (_charStack, _index) {
    while(true) {
      var index = _index;
      var charStack = _charStack;
      if (index === 3) {
        var firstChar = charStack.charAt(0);
        var secondChar = charStack.charAt(1);
        var thirdChar = charStack.charAt(2);
        if (firstChar === secondChar || secondChar === thirdChar || firstChar === thirdChar) {
          return 0;
        } else {
          return 1;
        }
      }
      var $$char = str.charAt(index);
      _index = index + 1 | 0;
      _charStack = charStack.concat($$char);
      continue ;
    };
  };
  var _goodSubstringsCount = expandWindow("", 0);
  var _leftIndex = 1;
  var _rightIndex = 3;
  while(true) {
    var rightIndex = _rightIndex;
    var leftIndex = _leftIndex;
    var goodSubstringsCount = _goodSubstringsCount;
    if (rightIndex === str.length) {
      return goodSubstringsCount;
    }
    var windowStr = str.slice(leftIndex, leftIndex + 3 | 0).concat(str.charAt(rightIndex));
    var firstChar = windowStr.charAt(0);
    var secondChar = windowStr.charAt(1);
    var thirdChar = windowStr.charAt(2);
    _rightIndex = rightIndex + 1 | 0;
    _leftIndex = leftIndex + 1 | 0;
    _goodSubstringsCount = firstChar === secondChar || secondChar === thirdChar || firstChar === thirdChar ? goodSubstringsCount : goodSubstringsCount + 1 | 0;
    continue ;
  };
}

var s1 = "xyzzaz";

var r1 = substringsSizeThreeDistinctChars(s1);

console.log("r1: ", r1);

var s2 = "aababcabc";

var r2 = substringsSizeThreeDistinctChars(s2);

console.log("r2: ", r2);

var s3 = "abc";

var r3 = substringsSizeThreeDistinctChars(s3);

console.log("r3: ", r3);

export {
  substringsSizeThreeDistinctChars ,
  s1 ,
  r1 ,
  s2 ,
  r2 ,
  s3 ,
  r3 ,
}
/* r1 Not a pure module */
