// Generated by ReScript, PLEASE EDIT WITH CARE


function antOnTheBoundary(nums) {
  var _count = 0;
  var _position = 0;
  var _index = 0;
  while(true) {
    var index = _index;
    var position = _position;
    var count = _count;
    var newCount = position === 0 && index !== 0 ? count + 1 | 0 : count;
    if (index === nums.length) {
      return newCount;
    }
    var n = nums.at(index);
    var num = n !== undefined ? n : -11;
    _index = index + 1 | 0;
    _position = position + num | 0;
    _count = newCount;
    continue ;
  };
}

var n1 = [
  2,
  3,
  -5
];

var r1 = antOnTheBoundary(n1);

console.log("r1: ", r1);

var n2 = [
  3,
  2,
  -3,
  -4
];

var r2 = antOnTheBoundary(n2);

console.log("r2: ", r2);

export {
  antOnTheBoundary ,
  n1 ,
  r1 ,
  n2 ,
  r2 ,
}
/* r1 Not a pure module */
