// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.res.js";

function buyTwoChocolates(prices, money) {
  var first = Core__Option.mapOr(prices.at(0), 0, (function (p) {
          return p;
        }));
  var second = Core__Option.mapOr(prices.at(1), 0, (function (p) {
          return p;
        }));
  var firstMinimum = first < second ? first : second;
  var secondMinimum = first > second ? first : second;
  var minimize = function (_firstMinimum, _secondMinimum, _index) {
    while(true) {
      var index = _index;
      var secondMinimum = _secondMinimum;
      var firstMinimum = _firstMinimum;
      if (index === prices.length) {
        return [
                firstMinimum,
                secondMinimum
              ];
      }
      var price = Core__Option.mapOr(prices.at(index), 0, (function (p) {
              return p;
            }));
      if (price < firstMinimum) {
        _index = index + 1 | 0;
        _secondMinimum = firstMinimum;
        _firstMinimum = price;
        continue ;
      }
      if (price < secondMinimum) {
        _index = index + 1 | 0;
        _firstMinimum = price;
        continue ;
      }
      _index = index + 1 | 0;
      continue ;
    };
  };
  var match = minimize(firstMinimum, secondMinimum, 2);
  var secondMin = match[1];
  var firstMin = match[0];
  if ((firstMin + secondMin | 0) <= money) {
    return money - (firstMin + secondMin | 0) | 0;
  } else {
    return money;
  }
}

var p1 = [
  1,
  2,
  2
];

var r1 = buyTwoChocolates(p1, 3);

console.log("r1: ", r1);

var p2 = [
  3,
  2,
  3
];

var r2 = buyTwoChocolates(p2, 3);

console.log("r2: ", r2);

var m1 = 3;

var m2 = 3;

export {
  buyTwoChocolates ,
  p1 ,
  m1 ,
  r1 ,
  p2 ,
  m2 ,
  r2 ,
}
/* r1 Not a pure module */
