// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.res.js";

function chunkArray(arr, size) {
  if (arr.length === 0) {
    return [];
  } else {
    var _chunks = [];
    var _chunk = [];
    var _index = 0;
    while(true) {
      var index = _index;
      var chunk = _chunk;
      var chunks = _chunks;
      if (index === arr.length) {
        return chunks.concat([chunk]);
      }
      var num = Core__Option.mapOr(arr.at(index), 0, (function (n) {
              return n;
            }));
      if (chunk.length === size) {
        _index = index + 1 | 0;
        _chunk = [num];
        _chunks = chunks.concat([chunk]);
        continue ;
      }
      _index = index + 1 | 0;
      _chunk = chunk.concat([num]);
      continue ;
    };
  }
}

var a1 = [
  1,
  2,
  3,
  4,
  5
];

var r1 = chunkArray(a1, 1);

console.log("r1: ", r1);

var a2 = [
  1,
  9,
  6,
  3,
  2
];

var r2 = chunkArray(a2, 3);

console.log("r2: ", r2);

var a3 = [
  8,
  5,
  3,
  2,
  6
];

var r3 = chunkArray(a3, 6);

console.log("r3: ", r3);

var a4 = [];

var r4 = chunkArray(a4, 1);

console.log("r4: ", r4);

var s1 = 1;

var s2 = 3;

var s3 = 6;

var s4 = 1;

export {
  chunkArray ,
  a1 ,
  s1 ,
  r1 ,
  a2 ,
  s2 ,
  r2 ,
  a3 ,
  s3 ,
  r3 ,
  a4 ,
  s4 ,
  r4 ,
}
/* r1 Not a pure module */
