// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Int from "@rescript/core/src/Core__Int.res.js";
import * as Core__Array from "@rescript/core/src/Core__Array.res.js";

function countNumberOfDistinctIntegersAfterReverseOps(nums) {
  var reverseDigits = function (num) {
    var numStr = num.toString();
    var length = numStr.length;
    var _reversed = String();
    var numStr$1 = num.toString();
    var _index = length - 1 | 0;
    while(true) {
      var index = _index;
      var reversed = _reversed;
      if (index < 0) {
        var s = Core__Int.fromString(reversed, undefined);
        if (s !== undefined) {
          return s;
        } else {
          return 0;
        }
      }
      _index = index - 1 | 0;
      _reversed = reversed.concat(numStr$1.charAt(index));
      continue ;
    };
  };
  var distincts = new Set();
  var _index = 0;
  while(true) {
    var index = _index;
    if (index === nums.length) {
      return Core__Array.reduce(nums, distincts, (function (set, num) {
                    set.add(num);
                    return set;
                  })).size;
    }
    var n = nums.at(index);
    var num = n !== undefined ? n : 0;
    distincts.add(reverseDigits(num));
    _index = index + 1 | 0;
    continue ;
  };
}

var n1 = [
  1,
  13,
  10,
  12,
  31
];

var r1 = countNumberOfDistinctIntegersAfterReverseOps(n1);

console.log("r1: ", r1);

var n2 = [
  2,
  2,
  2
];

var r2 = countNumberOfDistinctIntegersAfterReverseOps(n2);

console.log("r2: ", r2);

export {
  countNumberOfDistinctIntegersAfterReverseOps ,
  n1 ,
  r1 ,
  n2 ,
  r2 ,
}
/* r1 Not a pure module */
