// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Int from "@rescript/core/src/Core__Int.res.js";

function divideArrayIntoSubarraysWithMinCost_I(nums) {
  var n = nums.at(0);
  var cost = n !== undefined ? n : 0;
  var sorted = nums.slice(1, nums.length).toSorted(function (a, b) {
        return Core__Int.compare(a, b);
      });
  var n$1 = sorted.at(0);
  var firstMin = n$1 !== undefined ? n$1 : 0;
  var n$2 = sorted.at(1);
  var secondMin = n$2 !== undefined ? n$2 : 0;
  return (cost + firstMin | 0) + secondMin | 0;
}

var n1 = [
  1,
  2,
  3,
  12
];

var r1 = divideArrayIntoSubarraysWithMinCost_I(n1);

console.log("r1: ", r1);

var n2 = [
  5,
  4,
  3
];

var r2 = divideArrayIntoSubarraysWithMinCost_I(n2);

console.log("r2: ", r2);

var n3 = [
  10,
  3,
  1,
  1
];

var r3 = divideArrayIntoSubarraysWithMinCost_I(n3);

console.log("r3: ", r3);

export {
  divideArrayIntoSubarraysWithMinCost_I ,
  n1 ,
  r1 ,
  n2 ,
  r2 ,
  n3 ,
  r3 ,
}
/* r1 Not a pure module */
