// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Int32 from "rescript/lib/es6/int32.js";

function findIntegerAddedToArray_I(nums1, nums2) {
  var findMin = function (_min, nums, _index) {
    while(true) {
      var index = _index;
      var min = _min;
      if (index === nums.length) {
        return min;
      }
      var n = nums.at(index);
      var num = n !== undefined ? n : Int32.max_int;
      _index = index + 1 | 0;
      _min = min < num ? min : num;
      continue ;
    };
  };
  var min1 = findMin(Int32.max_int, nums1, 0);
  var min2 = findMin(Int32.max_int, nums2, 0);
  return min2 - min1 | 0;
}

var n1 = [
  2,
  6,
  4
];

var n11 = [
  9,
  7,
  5
];

var r1 = findIntegerAddedToArray_I(n1, n11);

console.log("r1: ", r1);

var n2 = [10];

var n22 = [5];

var r2 = findIntegerAddedToArray_I(n2, n22);

console.log("r2: ", r2);

var n3 = [
  1,
  1,
  1,
  1
];

var n33 = [
  1,
  1,
  1,
  1
];

var r3 = findIntegerAddedToArray_I(n3, n33);

console.log("r3: ", r3);

export {
  findIntegerAddedToArray_I ,
  n1 ,
  n11 ,
  r1 ,
  n2 ,
  n22 ,
  r2 ,
  n3 ,
  n33 ,
  r3 ,
}
/* r1 Not a pure module */
