// Generated by ReScript, PLEASE EDIT WITH CARE


function firstLetterToAppearTwice(str) {
  var _letter = "";
  var seen = new Set();
  var _index = 0;
  while(true) {
    var index = _index;
    var letter = _letter;
    if (index === str.length || letter !== "") {
      return letter;
    }
    var $$char = str.charAt(index);
    var hasSeen = seen.has($$char);
    if (hasSeen) {
      _index = index + 1 | 0;
      _letter = $$char;
      continue ;
    }
    seen.add($$char);
    _index = index + 1 | 0;
    _letter = "";
    continue ;
  };
}

var s1 = "abccbaacz";

var r1 = firstLetterToAppearTwice(s1);

console.log("r1: ", r1);

var s2 = "abcdd";

var r2 = firstLetterToAppearTwice(s2);

console.log("r2: ", r2);

export {
  firstLetterToAppearTwice ,
  s1 ,
  r1 ,
  s2 ,
  r2 ,
}
/* r1 Not a pure module */
