// Generated by ReScript, PLEASE EDIT WITH CARE


function join(strings, spacerOpt) {
  var spacer = spacerOpt !== undefined ? spacerOpt : " ";
  var _accumulator = "";
  var _rest = strings;
  var _index = 0;
  while(true) {
    var index = _index;
    var rest = _rest;
    var accumulator = _accumulator;
    var length = rest.length;
    if (length === 0) {
      return accumulator;
    }
    var str = rest[0];
    var head = str !== undefined ? str : "";
    var sliced = rest.slice(1, length);
    if (index === 0 || index === length) {
      _index = index + 1 | 0;
      _rest = sliced;
      _accumulator = accumulator + head;
      continue ;
    }
    _index = index + 1 | 0;
    _rest = sliced;
    _accumulator = accumulator + spacer + head;
    continue ;
  };
}

var strings = [
  "Hello",
  "Athma",
  "!",
  "How",
  "are",
  "you",
  "?"
];

var result = join(strings, undefined);

console.log("join", result);

export {
  join ,
  strings ,
  result ,
}
/* result Not a pure module */
