// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Int32 from "rescript/lib/es6/int32.js";

function leadersInAnArray(nums) {
  var _leaders = [];
  var _max = Int32.min_int;
  var _index = nums.length - 1 | 0;
  while(true) {
    var index = _index;
    var max = _max;
    var leaders = _leaders;
    if (index < 0) {
      return leaders;
    }
    var n = nums.at(index);
    var num = n !== undefined ? n : Int32.min_int;
    if (num > max) {
      _index = index - 1 | 0;
      _max = num;
      _leaders = [num].concat(leaders);
      continue ;
    }
    _index = index - 1 | 0;
    continue ;
  };
}

var n1 = [
  16,
  17,
  4,
  3,
  5,
  2
];

var r1 = leadersInAnArray(n1);

console.log("r1: ", r1);

var n2 = [
  1,
  2,
  3,
  4,
  5,
  2
];

var r2 = leadersInAnArray(n2);

console.log("r2: ", r2);

export {
  leadersInAnArray ,
  n1 ,
  r1 ,
  n2 ,
  r2 ,
}
/* r1 Not a pure module */
