// Generated by ReScript, PLEASE EDIT WITH CARE


function maxAreaOfLongestDiagonalRectangle(dimensions) {
  var findIdxOfLongestDiagonal = function (_idxOfLongestDiagonal, _longestDiagonal, _index) {
    while(true) {
      var index = _index;
      var longestDiagonal = _longestDiagonal;
      var idxOfLongestDiagonal = _idxOfLongestDiagonal;
      if (index === dimensions.length) {
        return idxOfLongestDiagonal;
      }
      var d = dimensions.at(index);
      var match = d !== undefined ? d : [
          0,
          0
        ];
      var width = match[1];
      var length = match[0];
      var squareArea = Math.imul(length, length) + Math.imul(width, width) | 0;
      var currDiagonal = Math.sqrt(squareArea);
      var match$1 = longestDiagonal > currDiagonal ? [
          longestDiagonal,
          idxOfLongestDiagonal
        ] : [
          currDiagonal,
          index
        ];
      _index = index + 1 | 0;
      _longestDiagonal = match$1[0];
      _idxOfLongestDiagonal = match$1[1];
      continue ;
    };
  };
  var idxOfLongestDiagonal = findIdxOfLongestDiagonal(-1, -1.0, 0);
  var d = dimensions.at(idxOfLongestDiagonal);
  var match = d !== undefined ? d : [
      0,
      0
    ];
  return Math.imul(match[0], match[1]);
}

var d1 = [
  [
    9,
    3
  ],
  [
    8,
    6
  ]
];

var r1 = maxAreaOfLongestDiagonalRectangle(d1);

console.log("r1: ", r1);

var d2 = [
  [
    3,
    4
  ],
  [
    4,
    3
  ]
];

var r2 = maxAreaOfLongestDiagonalRectangle(d2);

console.log("r2: ", r2);

export {
  maxAreaOfLongestDiagonalRectangle ,
  d1 ,
  r1 ,
  d2 ,
  r2 ,
}
/* r1 Not a pure module */
