// Generated by ReScript, PLEASE EDIT WITH CARE


function minimumOperationsToCollectElements(nums, k) {
  var _ops = 0;
  var _tracker = k;
  var _sliced = nums.map(function (n) {
        return n;
      });
  while(true) {
    var sliced = _sliced;
    var tracker = _tracker;
    var ops = _ops;
    var length = sliced.length;
    if (tracker === 0 || length === 0) {
      return ops;
    }
    var n = sliced.at(-1);
    var num = n !== undefined ? n : 0;
    _sliced = sliced.slice(0, length - 1 | 0);
    _tracker = num <= k ? tracker - 1 | 0 : tracker;
    _ops = ops + 1 | 0;
    continue ;
  };
}

var n1 = [
  3,
  1,
  5,
  4,
  2
];

var r1 = minimumOperationsToCollectElements(n1, 2);

console.log("r1: ", r1);

var n2 = [
  3,
  1,
  5,
  4,
  2
];

var r2 = minimumOperationsToCollectElements(n2, 5);

console.log("r2: ", r2);

var n3 = [
  3,
  2,
  5,
  3,
  1
];

var r3 = minimumOperationsToCollectElements(n3, 3);

console.log("r3: ", r3);

var k1 = 2;

var k2 = 5;

var k3 = 3;

export {
  minimumOperationsToCollectElements ,
  n1 ,
  k1 ,
  r1 ,
  n2 ,
  k2 ,
  r2 ,
  n3 ,
  k3 ,
  r3 ,
}
/* r1 Not a pure module */
