// Generated by ReScript, PLEASE EDIT WITH CARE


function minOpsToExceedThresholdValue_I(nums, k) {
  var _operations = 0;
  var _index = 0;
  while(true) {
    var index = _index;
    var operations = _operations;
    if (index === nums.length) {
      return operations;
    }
    var n = nums.at(index);
    var num = n !== undefined ? n : 0;
    _index = index + 1 | 0;
    _operations = num >= k ? operations : operations + 1 | 0;
    continue ;
  };
}

var n1 = [
  2,
  11,
  10,
  1,
  3
];

var r1 = minOpsToExceedThresholdValue_I(n1, 10);

console.log("r1: ", r1);

var n2 = [
  1,
  1,
  2,
  4,
  9
];

var r2 = minOpsToExceedThresholdValue_I(n2, 1);

console.log("r2: ", r2);

var n3 = [
  1,
  1,
  2,
  4,
  9
];

var r3 = minOpsToExceedThresholdValue_I(n3, 9);

console.log("r3: ", r3);

var k1 = 10;

var k2 = 1;

var k3 = 9;

export {
  minOpsToExceedThresholdValue_I ,
  n1 ,
  k1 ,
  r1 ,
  n2 ,
  k2 ,
  r2 ,
  n3 ,
  k3 ,
  r3 ,
}
/* r1 Not a pure module */
