// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Int from "@rescript/core/src/Core__Int.res.js";
import * as Core__Array from "@rescript/core/src/Core__Array.res.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.js";

function numberOfSeniorCitizens(details) {
  var collect = function (_ages, _index) {
    while(true) {
      var index = _index;
      var ages = _ages;
      if (index === details.length) {
        return ages;
      }
      _index = index + 1 | 0;
      _ages = ages.concat([Core__Option.mapOr(details.at(index), String(), (function (detail) {
                    return detail.slice(11, 13);
                  }))]);
      continue ;
    };
  };
  return Core__Array.reduce(collect([], 0), 0, (function (acc, age) {
                if (Core__Option.mapOr(Core__Int.fromString(age, undefined), 0, (function (a) {
                          return a;
                        })) > 60) {
                  return acc + 1 | 0;
                } else {
                  return acc;
                }
              }));
}

var d1 = [
  "7868190130M7522",
  "5303914400F9211",
  "9273338290F4010"
];

var r1 = numberOfSeniorCitizens(d1);

console.log("r1: ", r1);

var d2 = [
  "1313579440F2036",
  "2921522980M5644"
];

var r2 = numberOfSeniorCitizens(d2);

console.log("r2: ", r2);

export {
  numberOfSeniorCitizens ,
  d1 ,
  r1 ,
  d2 ,
  r2 ,
}
/* r1 Not a pure module */
