// Generated by ReScript, PLEASE EDIT WITH CARE


function wateringPlants(plants, capacity) {
  var _steps = 0;
  var _can = capacity;
  var _index = 0;
  while(true) {
    var index = _index;
    var can = _can;
    var steps = _steps;
    if (index === plants.length) {
      return steps;
    }
    var r = plants.at(index);
    var req = r !== undefined ? r : 0;
    if (can < req || can <= 0) {
      _can = capacity;
      _steps = steps + (index << 1) | 0;
      continue ;
    }
    _index = index + 1 | 0;
    _can = can - req | 0;
    _steps = steps + 1 | 0;
    continue ;
  };
}

var p1 = [
  2,
  2,
  3,
  3
];

var r1 = wateringPlants(p1, 5);

console.log("r1: ", r1);

var p2 = [
  1,
  1,
  1,
  4,
  2,
  3
];

var r2 = wateringPlants(p2, 4);

console.log("r2: ", r2);

var c1 = 5;

var c2 = 4;

export {
  wateringPlants ,
  p1 ,
  c1 ,
  r1 ,
  p2 ,
  c2 ,
  r2 ,
}
/* r1 Not a pure module */
