// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Int32 from "rescript/lib/es6/int32.js";
import * as Core__Array from "@rescript/core/src/Core__Array.res.js";

function dailyTemperatures(temps) {
  var length = temps.length;
  var updateDaysAndStack = function (daysToWait, _monoDecrStack, indexToPush) {
    while(true) {
      var monoDecrStack = _monoDecrStack;
      var stackLength = monoDecrStack.length;
      var num = temps[indexToPush];
      var numToPush = num !== undefined ? num : Int32.min_int;
      var num$1 = monoDecrStack.at(-1);
      var prevMinimumIndex = num$1 !== undefined ? num$1 : -1;
      var num$2 = temps[prevMinimumIndex];
      var prevMinimum = num$2 !== undefined ? num$2 : Int32.max_int;
      console.log("--updateDaysAndStack--");
      console.log("daysToWait: ", daysToWait);
      console.log("indexToPush: ", indexToPush);
      console.log("numToPush: ", numToPush);
      console.log("prevMinimumIndex: ", prevMinimumIndex);
      console.log("prevMinimum: ", prevMinimum);
      if (numToPush < prevMinimum) {
        return [
                daysToWait,
                monoDecrStack.concat([indexToPush])
              ];
      }
      daysToWait[prevMinimumIndex] = indexToPush - prevMinimumIndex | 0;
      _monoDecrStack = monoDecrStack.slice(1, stackLength);
      continue ;
    };
  };
  var _daysToWait = Core__Array.make(length, -1);
  var _monoDecrStack = [];
  var _index = 0;
  while(true) {
    var index = _index;
    var monoDecrStack = _monoDecrStack;
    var daysToWait = _daysToWait;
    if (index === length) {
      return daysToWait;
    }
    console.log("--loop--");
    console.log("daysToWait: ", daysToWait);
    console.log("monoDecrStack: ", monoDecrStack);
    var match = updateDaysAndStack(daysToWait, monoDecrStack, index);
    var updatedMonoDecrStack = match[1];
    var updatedDaysToWait = match[0];
    console.log("updatedDaysToWait: ", updatedDaysToWait);
    console.log("updatedMonoDecrStack: ", updatedMonoDecrStack);
    _index = index + 1 | 0;
    _monoDecrStack = updatedMonoDecrStack;
    _daysToWait = updatedDaysToWait;
    continue ;
  };
}

var t1 = [
  73,
  74,
  75,
  71,
  69,
  72,
  76,
  73
];

var r1 = dailyTemperatures(t1);

console.log("r1: ", r1);

export {
  dailyTemperatures ,
  t1 ,
  r1 ,
}
/* r1 Not a pure module */
