// Generated by ReScript, PLEASE EDIT WITH CARE


function numberOfLaserBeamsInABank(bank) {
  var _amount = 0;
  var _prevDeviceCount = 0;
  var _rowIndex = 0;
  while(true) {
    var rowIndex = _rowIndex;
    var prevDeviceCount = _prevDeviceCount;
    var amount = _amount;
    if (rowIndex === bank.length) {
      return amount;
    }
    var r = bank.at(rowIndex);
    var row = r !== undefined ? r : String();
    var checkDevicesCount = (function(row){
    return function checkDevicesCount(_devicesCount, _cellIndex) {
      while(true) {
        var cellIndex = _cellIndex;
        var devicesCount = _devicesCount;
        if (cellIndex === row.length) {
          return devicesCount;
        }
        var cell = row.charAt(cellIndex);
        if (cell === "0") {
          _cellIndex = cellIndex + 1 | 0;
          continue ;
        }
        _cellIndex = cellIndex + 1 | 0;
        _devicesCount = devicesCount + 1 | 0;
        continue ;
      };
    }
    }(row));
    var devicesCount = checkDevicesCount(0, 0);
    if (devicesCount > 0) {
      _rowIndex = rowIndex + 1 | 0;
      _prevDeviceCount = devicesCount;
      _amount = prevDeviceCount > 0 ? amount + Math.imul(devicesCount, prevDeviceCount) | 0 : amount;
      continue ;
    }
    _rowIndex = rowIndex + 1 | 0;
    continue ;
  };
}

var b1 = [
  "011001",
  "000000",
  "010100",
  "001000"
];

var r1 = numberOfLaserBeamsInABank(b1);

console.log("r1: ", r1);

var b2 = [
  "000",
  "111",
  "000"
];

var r2 = numberOfLaserBeamsInABank(b2);

console.log("r2: ", r2);

export {
  numberOfLaserBeamsInABank ,
  b1 ,
  r1 ,
  b2 ,
  r2 ,
}
/* r1 Not a pure module */
