// Generated by ReScript, PLEASE EDIT WITH CARE


function snakeInMatrix(n, commandsArr) {
  var _position = 0;
  var _x = 0;
  var _y = 0;
  var _index = 0;
  while(true) {
    var index = _index;
    var y = _y;
    var x = _x;
    var position = _position;
    if (index === commandsArr.length) {
      return position;
    }
    var c = commandsArr.at(index);
    var command = c !== undefined ? c : "UP";
    switch (command) {
      case "UP" :
          _index = index + 1 | 0;
          _y = y + 1 | 0;
          _position = position - n | 0;
          continue ;
      case "RIGHT" :
          _index = index + 1 | 0;
          _x = x + 1 | 0;
          _position = position + 1 | 0;
          continue ;
      case "DOWN" :
          _index = index + 1 | 0;
          _y = y - 1 | 0;
          _position = position + n | 0;
          continue ;
      case "LEFT" :
          _index = index + 1 | 0;
          _x = x - 1 | 0;
          _position = position - 1 | 0;
          continue ;
      
    }
  };
}

var c1 = [
  "RIGHT",
  "DOWN"
];

var r1 = snakeInMatrix(2, c1);

console.log("r1: ", r1);

var c2 = [
  "DOWN",
  "RIGHT",
  "UP"
];

var r2 = snakeInMatrix(3, c2);

console.log("r2: ", r2);

var n1 = 2;

var n2 = 3;

export {
  snakeInMatrix ,
  n1 ,
  c1 ,
  r1 ,
  n2 ,
  c2 ,
  r2 ,
}
/* r1 Not a pure module */
