// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml from "rescript/lib/es6/caml.js";

function sortStudentsByTheirKthScore(scores, k) {
  return scores.toSorted(function (row1, row2) {
              var s = row1.at(k);
              var score1 = s !== undefined ? s : -1;
              var s$1 = row2.at(k);
              var score2 = s$1 !== undefined ? s$1 : -1;
              return Caml.int_compare(score2, score1);
            });
}

var s1 = [
  [
    10,
    6,
    9,
    1
  ],
  [
    7,
    5,
    11,
    2
  ],
  [
    4,
    8,
    3,
    15
  ]
];

var r1 = sortStudentsByTheirKthScore(s1, 2);

console.log("r1: ", r1);

var s2 = [
  [
    3,
    4
  ],
  [
    5,
    6
  ]
];

var r2 = sortStudentsByTheirKthScore(s2, 0);

console.log("r2: ", r2);

var k1 = 2;

var k2 = 0;

export {
  sortStudentsByTheirKthScore ,
  s1 ,
  k1 ,
  r1 ,
  s2 ,
  k2 ,
  r2 ,
}
/* r1 Not a pure module */
