// Generated by ReScript, PLEASE EDIT WITH CARE


function validPerfectSquare(num) {
  if (num > 0) {
    var _left = 1;
    var _right = num;
    while(true) {
      var right = _right;
      var left = _left;
      var middle = left + ((right - left | 0) / 2 | 0) | 0;
      var squared = Math.imul(middle, middle);
      if (left > right) {
        return false;
      }
      if (squared === num) {
        return true;
      }
      if (squared < num) {
        _left = middle + 1 | 0;
        continue ;
      }
      _right = middle - 1 | 0;
      continue ;
    };
  } else {
    return false;
  }
}

var r1 = validPerfectSquare(16);

console.log("r1: ", r1);

var r2 = validPerfectSquare(14);

console.log("r2: ", r2);

var n1 = 16;

var n2 = 14;

export {
  validPerfectSquare ,
  n1 ,
  r1 ,
  n2 ,
  r2 ,
}
/* r1 Not a pure module */
