// Generated by ReScript, PLEASE EDIT WITH CARE


function findTheDistinctDifferenceArray(nums) {
  var _diffArray = [];
  var _index = 0;
  while(true) {
    var index = _index;
    var diffArray = _diffArray;
    if (index === nums.length) {
      return diffArray;
    }
    var prefixes = new Set(nums.slice(0, index + 1 | 0)).size;
    var suffixes = new Set(nums.slice(index + 1 | 0)).size;
    _index = index + 1 | 0;
    _diffArray = diffArray.concat([prefixes - suffixes | 0]);
    continue ;
  };
}

var n1 = [
  1,
  2,
  3,
  4,
  5
];

var r1 = findTheDistinctDifferenceArray(n1);

console.log("r1: ", r1);

var n2 = [
  3,
  2,
  3,
  4,
  2
];

var r2 = findTheDistinctDifferenceArray(n2);

console.log("r2: ", r2);

export {
  findTheDistinctDifferenceArray ,
  n1 ,
  r1 ,
  n2 ,
  r2 ,
}
/* r1 Not a pure module */
