// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml from "rescript/lib/es6/caml.js";

function groupAnagrams(words) {
  var loop = function (grouped, _index) {
    while(true) {
      var index = _index;
      if (index === words.length) {
        return grouped;
      }
      var c = words.at(index);
      var word = c !== undefined ? c : "";
      var sorted = word.split("").toSorted(Caml.string_compare).join("");
      var g = grouped.get(sorted);
      var existingGroups = g !== undefined ? g : [];
      grouped.set(sorted, existingGroups.concat([word]));
      _index = index + 1 | 0;
      continue ;
    };
  };
  return Array.from(loop(new Map(), 0).values());
}

var s1 = [
  "eat",
  "tea",
  "tan",
  "ate",
  "nat",
  "bat"
];

var r1 = groupAnagrams(s1);

console.log("r1: ", r1);

var s2 = [""];

var r2 = groupAnagrams(s2);

console.log("r2: ", r2);

var s3 = ["a"];

var r3 = groupAnagrams(s3);

console.log("r3: ", r3);

export {
  groupAnagrams ,
  s1 ,
  r1 ,
  s2 ,
  r2 ,
  s3 ,
  r3 ,
}
/* r1 Not a pure module */
