// Generated by ReScript, PLEASE EDIT WITH CARE


function permutationDiffBetweenTwoStrings(s1, s2) {
  var s1Loop = function (indexTable, _index1) {
    while(true) {
      var index1 = _index1;
      if (index1 === s1.length) {
        return indexTable;
      }
      var $$char = s1.charAt(index1);
      indexTable.set($$char, index1);
      _index1 = index1 + 1 | 0;
      continue ;
    };
  };
  var indexTable = s1Loop(new Map(), 0);
  var _permutationDiff = 0;
  var _index2 = 0;
  while(true) {
    var index2 = _index2;
    var permutationDiff = _permutationDiff;
    if (index2 === s2.length) {
      return permutationDiff;
    }
    var $$char = s2.charAt(index2);
    var i = indexTable.get($$char);
    var charIdx = i !== undefined ? i : -1;
    var newDiff = charIdx - index2 | 0;
    var absDiff = newDiff < 0 ? Math.imul(newDiff, -1) : newDiff;
    _index2 = index2 + 1 | 0;
    _permutationDiff = permutationDiff + absDiff | 0;
    continue ;
  };
}

var s1 = "abc";

var s11 = "bac";

var r1 = permutationDiffBetweenTwoStrings(s1, s11);

console.log("r1: ", r1);

var s2 = "abcde";

var s22 = "edbac";

var r2 = permutationDiffBetweenTwoStrings(s2, s22);

console.log("r2: ", r2);

export {
  permutationDiffBetweenTwoStrings ,
  s1 ,
  s11 ,
  r1 ,
  s2 ,
  s22 ,
  r2 ,
}
/* r1 Not a pure module */
