// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Array from "@rescript/core/src/Core__Array.res.js";

function splitTheArray(nums) {
  var loop = function (freqTable, _index) {
    while(true) {
      var index = _index;
      if (index === nums.length) {
        return freqTable;
      }
      var n = nums.at(index);
      var num = n !== undefined ? n : 0;
      var c = freqTable.get(num);
      var existingCount = c !== undefined ? c : 0;
      freqTable.set(num, existingCount + 1 | 0);
      _index = index + 1 | 0;
      continue ;
    };
  };
  return Core__Array.reduce(Array.from(loop(new Map(), 0).values()), true, (function (acc, count) {
                if (count > 2) {
                  return false;
                } else {
                  return acc;
                }
              }));
}

var n1 = [
  1,
  1,
  2,
  2,
  3,
  4
];

var r1 = splitTheArray(n1);

console.log("r1: ", r1);

var n2 = [
  1,
  1,
  1,
  1
];

var r2 = splitTheArray(n2);

console.log("r2: ", r2);

export {
  splitTheArray ,
  n1 ,
  r1 ,
  n2 ,
  r2 ,
}
/* r1 Not a pure module */
