// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Array from "@rescript/core/src/Core__Array.res.js";

function validAnagram(s, t) {
  var modifyFreqTable = function (freqTable, _index) {
    while(true) {
      var index = _index;
      if (index === t.length) {
        return freqTable;
      }
      var tChar = t.charAt(index);
      var c = freqTable.get(tChar);
      var existingCount = c !== undefined ? c : 0;
      if (existingCount === 0) {
        return new Map();
      }
      freqTable.set(tChar, existingCount - 1 | 0);
      _index = index + 1 | 0;
      continue ;
    };
  };
  var freqTable = Core__Array.reduce(s.split(""), new Map(), (function (acc, $$char) {
          var c = acc.get($$char);
          var existingCount = c !== undefined ? c : 0;
          acc.set($$char, existingCount + 1 | 0);
          return acc;
        }));
  var modifiedFreqTable = modifyFreqTable(freqTable, 0);
  var sum = modifiedFreqTable.size === 0 ? -1 : Core__Array.reduce(Array.from(modifiedFreqTable.values()), 0, (function (acc, count) {
            return acc + count | 0;
          }));
  return sum === 0;
}

var s1 = "anagram";

var s11 = "nagaram";

var r1 = validAnagram(s1, s11);

console.log("r1: ", r1);

var s2 = "rat";

var s22 = "car";

var r2 = validAnagram(s2, s22);

console.log("r2: ", r2);

var s3 = "a";

var s33 = "ab";

var r3 = validAnagram(s3, s33);

console.log("r3: ", r3);

var s4 = "a";

var s44 = "a";

var r4 = validAnagram(s4, s44);

console.log("r4: ", r4);

export {
  validAnagram ,
  s1 ,
  s11 ,
  r1 ,
  s2 ,
  s22 ,
  r2 ,
  s3 ,
  s33 ,
  r3 ,
  s4 ,
  s44 ,
  r4 ,
}
/* r1 Not a pure module */
