// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Int32 from "rescript/lib/es6/int32.js";

function containerMostWater(heights) {
  var _maxArea = Int32.min_int;
  var _leftIndex = 0;
  var _rightIndex = heights.length - 1 | 0;
  while(true) {
    var rightIndex = _rightIndex;
    var leftIndex = _leftIndex;
    var maxArea = _maxArea;
    var height = heights[leftIndex];
    var leftHeight = height !== undefined ? height : Int32.min_int;
    var height$1 = heights[rightIndex];
    var rightHeight = height$1 !== undefined ? height$1 : Int32.min_int;
    var minHeight = Math.min(leftHeight, rightHeight) | 0;
    var length = rightIndex - leftIndex | 0;
    var area = Math.imul(minHeight, length);
    var newMaxArea = Math.max(area, maxArea) | 0;
    if (leftIndex === rightIndex) {
      return maxArea;
    }
    if (leftHeight < rightHeight) {
      _leftIndex = leftIndex + 1 | 0;
      _maxArea = newMaxArea;
      continue ;
    }
    _rightIndex = rightIndex - 1 | 0;
    _maxArea = newMaxArea;
    continue ;
  };
}

var h1 = [
  1,
  8,
  6,
  2,
  5,
  4,
  8,
  3,
  7
];

var r1 = containerMostWater(h1);

console.log("[1,8,6,2,5,4,8,3,7]", r1);

export {
  containerMostWater ,
  h1 ,
  r1 ,
}
/* r1 Not a pure module */
