// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Int32 from "rescript/lib/es6/int32.js";

function duplicateZeroes(nums) {
  var length = nums.length;
  var _index = 0;
  var _queue = [];
  while(true) {
    var queue = _queue;
    var index = _index;
    var num = nums[index];
    var currentNum = num !== undefined ? num : Int32.min_int;
    var newQueue = queue.concat(currentNum === 0 ? [
            0,
            0
          ] : [currentNum]);
    var num$1 = newQueue.shift();
    var popped = num$1 !== undefined ? num$1 : Int32.min_int;
    nums[index] = popped;
    if (index === (length - 1 | 0)) {
      return nums;
    }
    _queue = newQueue;
    _index = index + 1 | 0;
    continue ;
  };
}

var nums1 = [
  1,
  0,
  2,
  3,
  0,
  4,
  5,
  0
];

var result1 = duplicateZeroes(nums1);

console.log("nums1", result1);

export {
  duplicateZeroes ,
  nums1 ,
  result1 ,
}
/* result1 Not a pure module */
