// Generated by ReScript, PLEASE EDIT WITH CARE


function excelSheetColumnTitle(columnNumber) {
  var _columnTitle = String();
  var _remainder = columnNumber;
  while(true) {
    var remainder = _remainder;
    var columnTitle = _columnTitle;
    if (remainder < 1.0) {
      return columnTitle;
    }
    var num = (remainder - 1.0) % 26.0;
    var str = String.fromCharCode(num + 65.0 | 0);
    _remainder = Math.floor((remainder - num) / 26.0);
    _columnTitle = str.concat(columnTitle);
    continue ;
  };
}

var r1 = excelSheetColumnTitle(1);

console.log("r1: ", r1);

var r2 = excelSheetColumnTitle(28);

console.log("r2: ", r2);

var r3 = excelSheetColumnTitle(701);

console.log("r3: ", r3);

var s1 = 1;

var s2 = 28;

var s3 = 701;

export {
  excelSheetColumnTitle ,
  s1 ,
  r1 ,
  s2 ,
  r2 ,
  s3 ,
  r3 ,
}
/* r1 Not a pure module */
