// Generated by ReScript, PLEASE EDIT WITH CARE


function findTheEncryptedString(str, k) {
  var _encrypted = String();
  var _index = 0;
  while(true) {
    var index = _index;
    var encrypted = _encrypted;
    var length = str.length;
    if (index === length) {
      return encrypted;
    }
    var kthIndex = index + k | 0;
    var kthChar = str.charAt(kthIndex >= length ? kthIndex - (k + 1 | 0) | 0 : kthIndex);
    _index = index + 1 | 0;
    _encrypted = encrypted.concat(kthChar);
    continue ;
  };
}

var s1 = "dart";

var r1 = findTheEncryptedString(s1, 3);

console.log("r1: ", r1);

var s2 = "aaa";

var r2 = findTheEncryptedString(s2, 1);

console.log("r2: ", r2);

var k1 = 3;

var k2 = 1;

export {
  findTheEncryptedString ,
  s1 ,
  k1 ,
  r1 ,
  s2 ,
  k2 ,
  r2 ,
}
/* r1 Not a pure module */
