// Generated by ReScript, PLEASE EDIT WITH CARE


function harshadNumber(x) {
  var loop = function (_sum, _temp) {
    while(true) {
      var temp = _temp;
      var sum = _sum;
      if (temp < 1) {
        return sum;
      }
      var remainder = temp % 10.0;
      _temp = temp / 10 | 0;
      _sum = sum + (remainder | 0) | 0;
      continue ;
    };
  };
  var sum = loop(0, x);
  if (x % sum === 0.0) {
    return sum;
  } else {
    return -1;
  }
}

var r1 = harshadNumber(18);

console.log("r1: ", r1);

var r2 = harshadNumber(23);

console.log("r2: ", r2);

var x1 = 18;

var x2 = 23;

export {
  harshadNumber ,
  x1 ,
  r1 ,
  x2 ,
  r2 ,
}
/* r1 Not a pure module */
