// Generated by ReScript, PLEASE EDIT WITH CARE


function lengthLastWord(words) {
  var _charCount = 0;
  var _numOfSpaces = 0;
  var _prevChar = " ";
  var _index = words.length - 1 | 0;
  while(true) {
    var index = _index;
    var prevChar = _prevChar;
    var numOfSpaces = _numOfSpaces;
    var charCount = _charCount;
    if (numOfSpaces === 2) {
      return charCount - 1 | 0;
    }
    var ch = words[index];
    var $$char = ch !== undefined ? ch : " ";
    if ($$char === " ") {
      _index = index - 1 | 0;
      _prevChar = " ";
      continue ;
    }
    if (prevChar === " ") {
      _index = index - 1 | 0;
      _prevChar = $$char;
      _numOfSpaces = numOfSpaces + 1 | 0;
      _charCount = charCount + 1 | 0;
      continue ;
    }
    _index = index - 1 | 0;
    _prevChar = $$char;
    _charCount = charCount + 1 | 0;
    continue ;
  };
}

var s1 = "Hello World ";

var r1 = lengthLastWord(s1);

console.log("r1: ", r1);

var s2 = "   fly me   to   the moon  ";

var r2 = lengthLastWord(s2);

console.log("r2: ", r2);

var s3 = "luffy is still joyboy";

var r3 = lengthLastWord(s3);

console.log("r3: ", r3);

export {
  lengthLastWord ,
  s1 ,
  r1 ,
  s2 ,
  r2 ,
  s3 ,
  r3 ,
}
/* r1 Not a pure module */
