// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Int32 from "rescript/lib/es6/int32.js";

function minDistanceToTargetElement(nums, target, start) {
  var _minDistance = Int32.max_int;
  var _index = 0;
  while(true) {
    var index = _index;
    var minDistance = _minDistance;
    if (index === nums.length) {
      return minDistance;
    }
    var n = nums.at(index);
    var num = n !== undefined ? n : Int32.max_int;
    if (num === target) {
      var newMinDistance = index - start | 0;
      _index = index + 1 | 0;
      _minDistance = newMinDistance < minDistance ? newMinDistance : minDistance;
      continue ;
    }
    _index = index + 1 | 0;
    continue ;
  };
}

var n1 = [
  1,
  2,
  3,
  4,
  5
];

var r1 = minDistanceToTargetElement(n1, 5, 3);

console.log("r1: ", r1);

var n2 = [1];

var r2 = minDistanceToTargetElement(n2, 1, 0);

console.log("r2: ", r2);

var n3 = [
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1
];

var r3 = minDistanceToTargetElement(n3, 1, 0);

console.log("r3: ", r3);

var t1 = 5;

var s1 = 3;

var t2 = 1;

var s2 = 0;

var t3 = 1;

var s3 = 0;

export {
  minDistanceToTargetElement ,
  n1 ,
  t1 ,
  s1 ,
  r1 ,
  n2 ,
  t2 ,
  s2 ,
  r2 ,
  n3 ,
  t3 ,
  s3 ,
  r3 ,
}
/* r1 Not a pure module */
