// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Int32 from "rescript/lib/es6/int32.js";
import * as Core__Int from "@rescript/core/src/Core__Int.res.js";

function minimumTimeDifference(timePoints) {
  var length = timePoints.length;
  var clone = timePoints.map(function (num) {
        return num;
      });
  clone.sort(function (a, b) {
        var compareFloat = a.localeCompare(b);
        if (compareFloat < 0.0) {
          return -1.0;
        } else if (compareFloat > 0.0) {
          return 1.0;
        } else {
          return 0.0;
        }
      });
  console.log("clone after sorting", clone);
  var _diff = Int32.max_int;
  var _index = 0;
  while(true) {
    var index = _index;
    var diff = _diff;
    var time = timePoints[index];
    var leftTimePoint = time !== undefined ? time : "";
    var leftSplitTime = leftTimePoint.split(":");
    var hrs = leftSplitTime[0];
    var leftHours = hrs !== undefined ? hrs : "";
    var mins = leftSplitTime[1];
    var leftMinutes = mins !== undefined ? mins : "";
    var hoursFloat = Core__Int.fromString(leftHours, undefined);
    var leftHoursFloat = hoursFloat !== undefined ? hoursFloat : Int32.min_int;
    var minutesFloat = Core__Int.fromString(leftMinutes, undefined);
    var leftMinutesFloat = minutesFloat !== undefined ? minutesFloat : Int32.min_int;
    var leftTotalSeconds = leftHoursFloat * 60.0 + leftMinutesFloat;
    console.log("leftTotalSeconds", leftTotalSeconds);
    var time$1 = timePoints[index + 1 | 0];
    var rightTimePoint = time$1 !== undefined ? time$1 : "";
    var rightSplitTime = rightTimePoint.split(":");
    var hrs$1 = rightSplitTime[0];
    var rightHours = hrs$1 !== undefined ? hrs$1 : "";
    var mins$1 = rightSplitTime[1];
    var rightMinutes = mins$1 !== undefined ? mins$1 : "";
    var hoursFloat$1 = Core__Int.fromString(rightHours, undefined);
    var rightHoursFloat = hoursFloat$1 !== undefined ? hoursFloat$1 : Int32.min_int;
    var minutesFloat$1 = Core__Int.fromString(rightMinutes, undefined);
    var rightMinutesFloat = minutesFloat$1 !== undefined ? minutesFloat$1 : Int32.min_int;
    var rightTotalSeconds = rightHoursFloat * 60.0 + rightMinutesFloat;
    console.log("rightTotalSeconds", rightTotalSeconds);
    if (index === (length - 2 | 0)) {
      return diff;
    }
    if (leftTotalSeconds === 0.0) {
      var midnightDiff = Math.abs(rightTotalSeconds - 1440.0);
      var zeroDiff = Math.abs(rightTotalSeconds - 0.0);
      if (midnightDiff < zeroDiff) {
        _index = index + 1 | 0;
        _diff = midnightDiff | 0;
        continue ;
      }
      _index = index + 1 | 0;
      _diff = zeroDiff | 0;
      continue ;
    }
    if (rightTotalSeconds === 0.0) {
      var midnightDiff$1 = Math.abs(1440.0 - leftTotalSeconds);
      var zeroDiff$1 = Math.abs(0.0 - leftTotalSeconds);
      if (midnightDiff$1 < zeroDiff$1) {
        _index = index + 1 | 0;
        _diff = midnightDiff$1 | 0;
        continue ;
      }
      _index = index + 1 | 0;
      _diff = zeroDiff$1 | 0;
      continue ;
    }
    var currentDiff = rightTotalSeconds - leftTotalSeconds;
    if ((currentDiff | 0) < diff) {
      _index = index + 1 | 0;
      _diff = currentDiff | 0;
      continue ;
    }
    _index = index + 1 | 0;
    continue ;
  };
}

var timePoints1 = [
  "23:59",
  "00:00"
];

var result1 = minimumTimeDifference(timePoints1);

console.log("result1", result1);

var timePoints2 = [
  "00:00",
  "23:59",
  "00:00"
];

var result2 = minimumTimeDifference(timePoints2);

console.log("result2", result2);

export {
  minimumTimeDifference ,
  timePoints1 ,
  result1 ,
  timePoints2 ,
  result2 ,
}
/* result1 Not a pure module */
