// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml from "rescript/lib/es6/caml.js";

function minNumberOfPushesToTypeWord_I(word) {
  var findFrequency = function (freqTable, _index) {
    while(true) {
      var index = _index;
      if (index === word.length) {
        return freqTable;
      }
      var $$char = word.charAt(index);
      var c = freqTable.get($$char);
      var existingCount = c !== undefined ? c : 0;
      freqTable.set($$char, existingCount + 1 | 0);
      _index = index + 1 | 0;
      continue ;
    };
  };
  var freqTable = findFrequency(new Map(), 0);
  var sorted = Array.from(freqTable.entries()).toSorted(function (param, param$1) {
        return Caml.int_compare(param$1[1], param[1]);
      });
  var _keyPress = 0;
  var _index = 0;
  while(true) {
    var index = _index;
    var keyPress = _keyPress;
    if (index === sorted.length) {
      return keyPress;
    }
    var t = sorted.at(index);
    var match = t !== undefined ? t : [
        String(),
        0
      ];
    _index = index + 1 | 0;
    _keyPress = Math.imul(match[1], (index / 8 | 0) + 1 | 0);
    continue ;
  };
}

var w1 = "abcde";

var r1 = minNumberOfPushesToTypeWord_I(w1);

console.log("r1: ", r1);

var w2 = "xycdefghij";

var r2 = minNumberOfPushesToTypeWord_I(w2);

console.log("r2: ", r2);

export {
  minNumberOfPushesToTypeWord_I ,
  w1 ,
  r1 ,
  w2 ,
  r2 ,
}
/* r1 Not a pure module */
