// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Int32 from "rescript/lib/es6/int32.js";

function moveZeroes(nums) {
  var length = nums.length;
  var _leftIndex = 0;
  var _rightIndex = 1;
  while(true) {
    var rightIndex = _rightIndex;
    var leftIndex = _leftIndex;
    var num = nums[leftIndex];
    var leftNum = num !== undefined ? num : Int32.min_int;
    var num$1 = nums[rightIndex];
    var rightNum = num$1 !== undefined ? num$1 : Int32.min_int;
    if (rightIndex === length) {
      return nums;
    }
    if (leftNum === 0) {
      if (rightNum === 0) {
        _rightIndex = rightIndex + 1 | 0;
        continue ;
      }
      nums[leftIndex] = rightNum;
      nums[rightIndex] = leftNum;
      var diff = rightIndex - leftIndex | 0;
      if (diff === 1) {
        _rightIndex = rightIndex + 1 | 0;
        _leftIndex = leftIndex + 1 | 0;
        continue ;
      }
      _leftIndex = leftIndex + 1 | 0;
      continue ;
    }
    var diff$1 = rightIndex - leftIndex | 0;
    if (diff$1 === 1) {
      _rightIndex = rightIndex + 1 | 0;
      _leftIndex = leftIndex + 1 | 0;
      continue ;
    }
    _leftIndex = leftIndex + 1 | 0;
    continue ;
  };
}

var n1 = [
  0,
  1,
  0,
  3,
  12
];

var r1 = moveZeroes(n1);

console.log("r1", r1);

export {
  moveZeroes ,
  n1 ,
  r1 ,
}
/* r1 Not a pure module */
