// Generated by ReScript, PLEASE EDIT WITH CARE


function optimalPartitionOfString(str) {
  var _partitioned = [];
  var _substring = new Set();
  var _index = 0;
  while(true) {
    var index = _index;
    var substring = _substring;
    var partitioned = _partitioned;
    if (index > str.length) {
      return partitioned.concat([Array.from(substring.values())]).length;
    }
    var $$char = str.charAt(index);
    if (substring.has($$char)) {
      _substring = new Set();
      _partitioned = partitioned.concat([Array.from(substring.values())]);
      continue ;
    }
    substring.add($$char);
    _index = index + 1 | 0;
    continue ;
  };
}

var s1 = "abacaba";

var r1 = optimalPartitionOfString(s1);

console.log("r1: ", r1);

var s2 = "ssssss";

var r2 = optimalPartitionOfString(s2);

console.log("r2: ", r2);

export {
  optimalPartitionOfString ,
  s1 ,
  r1 ,
  s2 ,
  r2 ,
}
/* r1 Not a pure module */
