// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.res.js";

function theEmployeeThatWorkedOnTheLongestTask(_n, logs) {
  var match = Core__Option.mapOr(logs.at(0), [
        -1,
        -1
      ], (function (t) {
          return t;
        }));
  var firstTask = match[1];
  var _id = match[0];
  var _longest = firstTask;
  var _prevTask = firstTask;
  var _index = 1;
  while(true) {
    var index = _index;
    var prevTask = _prevTask;
    var longest = _longest;
    var id = _id;
    if (index === logs.length) {
      return id;
    }
    var match$1 = Core__Option.mapOr(logs.at(index), [
          -1,
          -1
        ], (function (t) {
            return t;
          }));
    var currTask = match$1[1];
    var currId = match$1[0];
    var currTime = currTask - prevTask | 0;
    if (currTime > longest) {
      _index = index + 1 | 0;
      _prevTask = currTask;
      _longest = currTime;
      _id = currId;
      continue ;
    }
    if (currTime === longest) {
      _index = index + 1 | 0;
      _prevTask = currTask;
      _id = currId < id ? currId : id;
      continue ;
    }
    _index = index + 1 | 0;
    _prevTask = currTask;
    continue ;
  };
}

var l1 = [
  [
    0,
    3
  ],
  [
    2,
    5
  ],
  [
    0,
    9
  ],
  [
    1,
    15
  ]
];

var r1 = theEmployeeThatWorkedOnTheLongestTask(10, l1);

console.log("r1: ", r1);

var l2 = [
  [
    1,
    1
  ],
  [
    3,
    7
  ],
  [
    2,
    12
  ],
  [
    7,
    17
  ]
];

var r2 = theEmployeeThatWorkedOnTheLongestTask(26, l2);

console.log("r2: ", r2);

var l3 = [
  [
    0,
    10
  ],
  [
    1,
    20
  ]
];

var r3 = theEmployeeThatWorkedOnTheLongestTask(2, l3);

console.log("r3: ", r3);

var n1 = 10;

var n2 = 26;

var n3 = 2;

export {
  theEmployeeThatWorkedOnTheLongestTask ,
  n1 ,
  l1 ,
  r1 ,
  n2 ,
  l2 ,
  r2 ,
  n3 ,
  l3 ,
  r3 ,
}
/* r1 Not a pure module */
