// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Int32 from "rescript/lib/es6/int32.js";

function threeSum259(nums, target) {
  var length = nums.length;
  var clone = nums.map(function (num) {
        return num;
      });
  clone.sort(function (a, b) {
        return a - b | 0;
      });
  if (length < 3) {
    return 0;
  } else {
    var _result = 0;
    var _anchorIndex = 0;
    while(true) {
      var anchorIndex = _anchorIndex;
      var result = _result;
      var num = clone[anchorIndex];
      var currentAnchor = num !== undefined ? num : Int32.min_int;
      var explorersLoop = (function(currentAnchor){
      return function explorersLoop(_amountOfTriplets, _lowIndex, _highIndex) {
        while(true) {
          var highIndex = _highIndex;
          var lowIndex = _lowIndex;
          var amountOfTriplets = _amountOfTriplets;
          var num = clone[lowIndex];
          var lowExplorer = num !== undefined ? num : Int32.min_int;
          var num$1 = clone[highIndex];
          var highExplorer = num$1 !== undefined ? num$1 : Int32.min_int;
          var sum = (currentAnchor + lowExplorer | 0) + highExplorer | 0;
          if (lowIndex === highIndex) {
            return amountOfTriplets;
          }
          if (sum < target) {
            _highIndex = highIndex - 1 | 0;
            _amountOfTriplets = amountOfTriplets + 1 | 0;
            continue ;
          }
          if (sum > target) {
            _lowIndex = lowIndex + 1 | 0;
            continue ;
          }
          _highIndex = highIndex - 1 | 0;
          _lowIndex = lowIndex + 1 | 0;
          continue ;
        };
      }
      }(currentAnchor));
      var amountOfTriplets = explorersLoop(result, anchorIndex + 1 | 0, length - 1 | 0);
      if (anchorIndex === (length - 2 | 0)) {
        return amountOfTriplets;
      }
      _anchorIndex = anchorIndex + 1 | 0;
      _result = amountOfTriplets;
      continue ;
    };
  }
}

var n1 = [
  -2,
  0,
  1,
  3
];

var r1 = threeSum259(n1, 2);

console.log("[-2,0,1,3] 2", r1);

export {
  threeSum259 ,
  n1 ,
  r1 ,
}
/* r1 Not a pure module */
