// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Int32 from "rescript/lib/es6/int32.js";

function towerOfHanoi(startTower) {
  var amountOfDisks = startTower.length;
  var moveOneDisk = function (startTower, endTower) {
    var num = startTower.pop();
    var disk = num !== undefined ? num : Int32.min_int;
    endTower.push(disk);
  };
  var loop = function (_amountOfDisks, startTower, tempTower, endTower) {
    while(true) {
      var amountOfDisks = _amountOfDisks;
      if (amountOfDisks === 1) {
        return moveOneDisk(startTower, endTower);
      }
      loop(amountOfDisks - 1 | 0, startTower, endTower, tempTower);
      moveOneDisk(startTower, endTower);
      _amountOfDisks = amountOfDisks - 1 | 0;
      continue ;
    };
  };
  loop(amountOfDisks, startTower, [], []);
}

var t1 = [
  1,
  2,
  3
];

var r1 = towerOfHanoi(t1);

console.log("r1", r1);

export {
  towerOfHanoi ,
  t1 ,
  r1 ,
}
/* r1 Not a pure module */
