// Generated by ReScript, PLEASE EDIT WITH CARE


function twoSumII(nums, target) {
  var length = nums.length;
  var _leftIndex = 0;
  var _rightIndex = length - 1 | 0;
  while(true) {
    var rightIndex = _rightIndex;
    var leftIndex = _leftIndex;
    var num = nums[leftIndex];
    var leftNum = num !== undefined ? num : -1;
    var num$1 = nums[rightIndex];
    var rightNum = num$1 !== undefined ? num$1 : -1;
    var sum = leftNum + rightNum | 0;
    if (sum === target || leftIndex === rightIndex) {
      return [
              leftIndex + 1 | 0,
              rightIndex + 1 | 0
            ];
    }
    if (sum > target) {
      _rightIndex = rightIndex - 1 | 0;
      continue ;
    }
    _leftIndex = leftIndex + 1 | 0;
    continue ;
  };
}

var n1 = [
  2,
  7,
  11,
  15
];

var r1 = twoSumII(n1, 9);

console.log("r1", r1);

export {
  twoSumII ,
  n1 ,
  r1 ,
}
/* r1 Not a pure module */
