// Generated by ReScript, PLEASE EDIT WITH CARE


function twoSneakyNumbersOfDigitville(nums) {
  var _duplicates = [];
  var set = new Set();
  var _index = 0;
  while(true) {
    var index = _index;
    var duplicates = _duplicates;
    if (index === nums.length) {
      return duplicates;
    }
    var n = nums.at(index);
    var num = n !== undefined ? n : -1;
    if (set.has(num)) {
      _index = index + 1 | 0;
      _duplicates = duplicates.concat([num]);
      continue ;
    }
    set.add(num);
    _index = index + 1 | 0;
    continue ;
  };
}

var n1 = [
  0,
  1,
  1,
  0
];

var r1 = twoSneakyNumbersOfDigitville(n1);

console.log("r1: ", r1);

var n2 = [
  0,
  3,
  2,
  1,
  3,
  2
];

var r2 = twoSneakyNumbersOfDigitville(n2);

console.log("r2: ", r2);

var n3 = [
  7,
  1,
  5,
  4,
  3,
  4,
  6,
  0,
  9,
  5,
  8,
  2
];

var r3 = twoSneakyNumbersOfDigitville(n3);

console.log("r3: ", r3);

export {
  twoSneakyNumbersOfDigitville ,
  n1 ,
  r1 ,
  n2 ,
  r2 ,
  n3 ,
  r3 ,
}
/* r1 Not a pure module */
