// Generated by ReScript, PLEASE EDIT WITH CARE


function backspaceStringCompare(string1, string2) {
  var loop = function (_charStack, str, _index) {
    while(true) {
      var index = _index;
      var charStack = _charStack;
      var strLength = str.length;
      if (index === strLength) {
        return charStack;
      }
      var $$char = str[index];
      var currentChar = $$char !== undefined ? $$char : "";
      if (currentChar === "#") {
        _index = index + 1 | 0;
        _charStack = charStack.slice(0, charStack.length - 1 | 0);
        continue ;
      }
      _index = index + 1 | 0;
      _charStack = charStack.concat(currentChar);
      continue ;
    };
  };
  return loop("", string1, 0) === loop("", string2, 0);
}

var s1 = "ab#c";

var s11 = "ad#c";

var r1 = backspaceStringCompare(s1, s11);

console.log("r1: ", r1);

var s2 = "ab##";

var s22 = "c#d#";

var r2 = backspaceStringCompare(s2, s22);

console.log("r2: ", r2);

var s3 = "a##c";

var s33 = "#a#c";

var r3 = backspaceStringCompare(s3, s33);

console.log("r3: ", r3);

var s4 = "a#c";

var s44 = "b";

var r4 = backspaceStringCompare(s4, s44);

console.log("r4: ", r4);

export {
  backspaceStringCompare ,
  s1 ,
  s11 ,
  r1 ,
  s2 ,
  s22 ,
  r2 ,
  s3 ,
  s33 ,
  r3 ,
  s4 ,
  s44 ,
  r4 ,
}
/* r1 Not a pure module */
