// Generated by ReScript, PLEASE EDIT WITH CARE


function canPlaceFlowers(flowerbed, n) {
  var loop = function (_flowersRemaining, _stack, _index) {
    while(true) {
      var index = _index;
      var stack = _stack;
      var flowersRemaining = _flowersRemaining;
      if (index === flowerbed.length) {
        return flowersRemaining;
      }
      var i = stack.at(-1);
      var prevItemInPlot = i !== undefined ? i : -1;
      var i$1 = flowerbed.at(index);
      var currItemInPlot = i$1 !== undefined ? i$1 : -1;
      var i$2 = flowerbed.at(index + 1 | 0);
      var nextItemInPlot = i$2 !== undefined ? i$2 : -1;
      if (prevItemInPlot === 0 && currItemInPlot === 0 && nextItemInPlot === 0) {
        _index = index + 1 | 0;
        _stack = stack.concat([1]);
        _flowersRemaining = flowersRemaining - 1 | 0;
        continue ;
      }
      _index = index + 1 | 0;
      _stack = stack.concat([currItemInPlot]);
      continue ;
    };
  };
  return loop(n, [], 0) === 0;
}

var f1 = [
  1,
  0,
  0,
  0,
  1
];

var r1 = canPlaceFlowers(f1, 1);

console.log("r1=", r1);

var f2 = [
  1,
  0,
  0,
  0,
  1
];

var r2 = canPlaceFlowers(f2, 2);

console.log("r2=", r2);

var n1 = 1;

var n2 = 2;

export {
  canPlaceFlowers ,
  f1 ,
  n1 ,
  r1 ,
  f2 ,
  n2 ,
  r2 ,
}
/* r1 Not a pure module */
