// Generated by ReScript, PLEASE EDIT WITH CARE


function checkBinaryStringOneSegmentOfOnes(str) {
  var _amountOfOneSegments = 0;
  var _onesStack = "";
  var _index = 0;
  while(true) {
    var index = _index;
    var onesStack = _onesStack;
    var amountOfOneSegments = _amountOfOneSegments;
    if (index === str.length) {
      return amountOfOneSegments === 1;
    }
    var currentBinary = str.charAt(index);
    if (currentBinary === "0") {
      if (onesStack.length > 1) {
        _index = index + 1 | 0;
        _onesStack = "";
        _amountOfOneSegments = amountOfOneSegments + 1 | 0;
        continue ;
      }
      _index = index + 1 | 0;
      _onesStack = "";
      continue ;
    }
    _index = index + 1 | 0;
    _onesStack = onesStack.concat(currentBinary);
    continue ;
  };
}

var s1 = "1001";

var r1 = checkBinaryStringOneSegmentOfOnes(s1);

console.log("r1: ", r1);

var s2 = "110";

var r2 = checkBinaryStringOneSegmentOfOnes(s2);

console.log("r2: ", r2);

export {
  checkBinaryStringOneSegmentOfOnes ,
  s1 ,
  r1 ,
  s2 ,
  r2 ,
}
/* r1 Not a pure module */
