// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Int from "@rescript/core/src/Core__Int.res.js";

function clearDigits(str) {
  var _stack = String();
  var _index = 0;
  while(true) {
    var index = _index;
    var stack = _stack;
    if (index === str.length) {
      return stack;
    }
    var $$char = str.charAt(index);
    var n = Core__Int.fromString($$char, undefined);
    var charNum = n !== undefined ? n : -1;
    if (charNum < 0) {
      _index = index + 1 | 0;
      _stack = stack.concat($$char);
      continue ;
    }
    _index = index + 1 | 0;
    _stack = stack.slice(0, stack.length - 1 | 0);
    continue ;
  };
}

var s1 = "abc";

var r1 = clearDigits(s1);

console.log("r1: ", r1);

var s2 = "cb34";

var r2 = clearDigits(s2);

console.log("r2: ", r2);

export {
  clearDigits ,
  s1 ,
  r1 ,
  s2 ,
  r2 ,
}
/* r1 Not a pure module */
