// Generated by ReScript, PLEASE EDIT WITH CARE


function crawlerLogFolder(logs) {
  var length = logs.length;
  var _folders = [];
  var _index = 0;
  while(true) {
    var index = _index;
    var folders = _folders;
    var foldersLength = folders.length;
    if (index === length) {
      return foldersLength;
    }
    var l = logs[index];
    var log = l !== undefined ? l : "";
    switch (log) {
      case "../" :
          _index = index + 1 | 0;
          _folders = folders.slice(0, foldersLength - 1 | 0);
          continue ;
      case "./" :
          _index = index + 1 | 0;
          continue ;
      default:
        _index = index + 1 | 0;
        _folders = folders.concat([log]);
        continue ;
    }
  };
}

var l1 = [
  "d1/",
  "d2/",
  "../",
  "d21/",
  "./"
];

var r1 = crawlerLogFolder(l1);

console.log("r1: ", r1);

var l2 = [
  "d1/",
  "d2/",
  "./",
  "d3/",
  "../",
  "d31/"
];

var r2 = crawlerLogFolder(l2);

console.log("r2: ", r2);

var l3 = [
  "d1/",
  "../",
  "../",
  "../"
];

var r3 = crawlerLogFolder(l3);

console.log("r3: ", r3);

export {
  crawlerLogFolder ,
  l1 ,
  r1 ,
  l2 ,
  r2 ,
  l3 ,
  r3 ,
}
/* r1 Not a pure module */
