// Generated by ReScript, PLEASE EDIT WITH CARE


function deleteCharsToMakeFancyString(str) {
  var length = str.length;
  var _charStack = "";
  var _index = 0;
  var _counter = 0;
  while(true) {
    var counter = _counter;
    var index = _index;
    var charStack = _charStack;
    var charStackLength = charStack.length;
    if (index === length) {
      return charStack;
    }
    var previousChar = charStack.charAt(charStackLength - 1 | 0);
    var currentChar = str.charAt(index);
    if (currentChar === previousChar) {
      if (counter === 2) {
        _index = index + 1 | 0;
        continue ;
      }
      _counter = 2;
      _index = index + 1 | 0;
      _charStack = charStack.concat(currentChar);
      continue ;
    }
    _counter = 0;
    _index = index + 1 | 0;
    _charStack = charStack.concat(currentChar);
    continue ;
  };
}

var s1 = "leeetcode";

var r1 = deleteCharsToMakeFancyString(s1);

console.log("r1: ", r1);

var s2 = "aaabaaaa";

var r2 = deleteCharsToMakeFancyString(s2);

console.log("r2: ", r2);

export {
  deleteCharsToMakeFancyString ,
  s1 ,
  r1 ,
  s2 ,
  r2 ,
}
/* r1 Not a pure module */
