// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Int32 from "rescript/lib/es6/int32.js";
import * as Core__Int from "@rescript/core/src/Core__Int.res.js";

function numberOfDiffIntsInString(word) {
  var intSet = new Set();
  var _stack = "";
  var _index = 0;
  while(true) {
    var index = _index;
    var stack = _stack;
    if (index === word.length) {
      var n = Core__Int.fromString(stack, undefined);
      var num = n !== undefined ? n : Int32.min_int;
      if (num === Int32.min_int) {
        return intSet.size;
      } else {
        intSet.add(num);
        return intSet.size;
      }
    }
    var currentChar = word.charAt(index);
    var dig = Core__Int.fromString(currentChar, undefined);
    var currentDigit = dig !== undefined ? dig : -1;
    if (currentDigit < 0) {
      var n$1 = Core__Int.fromString(stack, undefined);
      var num$1 = n$1 !== undefined ? n$1 : Int32.min_int;
      if (num$1 === Int32.min_int) {
        _index = index + 1 | 0;
        _stack = "";
        continue ;
      }
      intSet.add(num$1);
      _index = index + 1 | 0;
      _stack = "";
      continue ;
    }
    _index = index + 1 | 0;
    _stack = stack.concat(currentChar);
    continue ;
  };
}

var w1 = "a123bc34d8ef34";

var r1 = numberOfDiffIntsInString(w1);

console.log("r1: ", r1);

export {
  numberOfDiffIntsInString ,
  w1 ,
  r1 ,
}
/* r1 Not a pure module */
