// Generated by ReScript, PLEASE EDIT WITH CARE


function scoreOfAString(str) {
  var _score = 0;
  var _stack = [];
  var _index = 0;
  while(true) {
    var index = _index;
    var stack = _stack;
    var score = _score;
    if (index === str.length) {
      return score;
    }
    var n = stack.at(-1);
    var prevCharCode = n !== undefined ? n : -1;
    var n$1 = str.codePointAt(index);
    var currCharCode = n$1 !== undefined ? n$1 : -1;
    var diff = prevCharCode - currCharCode | 0;
    var absDiff = diff < 0 ? Math.imul(diff, -1) : diff;
    _index = index + 1 | 0;
    _stack = stack.concat([currCharCode]);
    _score = prevCharCode < 0 ? score : score + absDiff | 0;
    continue ;
  };
}

var s1 = "hello";

var r1 = scoreOfAString(s1);

console.log("r1: ", r1);

var s2 = "zaz";

var r2 = scoreOfAString(s2);

console.log("r2: ", r2);

export {
  scoreOfAString ,
  s1 ,
  r1 ,
  s2 ,
  r2 ,
}
/* r1 Not a pure module */
