// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.res.js";

function splitStringsBySeparator(words, separator) {
  var splitStrings = function (_result, _wordsIndex) {
    while(true) {
      var wordsIndex = _wordsIndex;
      var result = _result;
      if (wordsIndex === words.length) {
        return result;
      }
      var word = Core__Option.mapOr(words.at(wordsIndex), String(), (function (w) {
              return w;
            }));
      var wordLoop = (function(word){
      return function wordLoop(_tempResult, _stack, _charIndex) {
        while(true) {
          var charIndex = _charIndex;
          var stack = _stack;
          var tempResult = _tempResult;
          if (charIndex === word.length) {
            return tempResult.concat([stack]);
          }
          var $$char = word.charAt(charIndex);
          if ($$char === separator) {
            _charIndex = charIndex + 1 | 0;
            _stack = String();
            _tempResult = tempResult.concat([stack]);
            continue ;
          }
          _charIndex = charIndex + 1 | 0;
          _stack = stack.concat($$char);
          continue ;
        };
      }
      }(word));
      var tempResult = wordLoop([], String(), 0);
      _wordsIndex = wordsIndex + 1 | 0;
      _result = result.concat(tempResult);
      continue ;
    };
  };
  return splitStrings([], 0).filter(function (w) {
              return w.length !== 0;
            });
}

var w1 = [
  "one.two.three",
  "four.five",
  "six"
];

var s1 = ".";

var r1 = splitStringsBySeparator(w1, s1);

console.log("r1: ", r1);

var w2 = [
  "$easy$",
  "$problem$"
];

var s2 = "$";

var r2 = splitStringsBySeparator(w2, s2);

console.log("r2: ", r2);

var w3 = ["|||"];

var s3 = "|";

var r3 = splitStringsBySeparator(w3, s3);

console.log("r3: ", r3);

export {
  splitStringsBySeparator ,
  w1 ,
  s1 ,
  r1 ,
  w2 ,
  s2 ,
  r2 ,
  w3 ,
  s3 ,
  r3 ,
}
/* r1 Not a pure module */
