// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Array from "@rescript/core/src/Core__Array.res.js";

function validPalindrome(str) {
  var alphaNumericSet = Core__Array.reduce("abcdefghijklmnopqrstuvwxyz0123456789".split(""), new Set(), (function (set, $$char) {
          set.add($$char);
          return set;
        }));
  var alphaNumericStr = Core__Array.reduce(str.toLowerCase().split(""), "", (function (acc, $$char) {
          if (alphaNumericSet.has($$char)) {
            return acc.concat($$char);
          } else {
            return acc;
          }
        }));
  var _sliced = alphaNumericStr;
  while(true) {
    var sliced = _sliced;
    if (sliced.length < 2) {
      return true;
    }
    var slicedLength = sliced.length;
    var firstChar = sliced.charAt(0);
    var lastChar = sliced.charAt(slicedLength - 1 | 0);
    if (firstChar !== lastChar) {
      return false;
    }
    _sliced = sliced.slice(1, slicedLength - 1 | 0);
    continue ;
  };
}

var s1 = "A man, a plan, a canal: Panama";

var r1 = validPalindrome(s1);

console.log("r1: ", r1);

var s2 = "race a car";

var r2 = validPalindrome(s2);

console.log("r2: ", r2);

var s3 = "";

var r3 = validPalindrome(s3);

console.log("r3: ", r3);

export {
  validPalindrome ,
  s1 ,
  r1 ,
  s2 ,
  r2 ,
  s3 ,
  r3 ,
}
/* r1 Not a pure module */
